### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by kqvanity** [nvim-neorg/rust-norg#17]
Could A CLI interface be introduced to interact with norg notes e.g., retrieve heading, their children, insert, etc.

**Comment by benlubas** [comment]
Probably better for a standalone tool that depends on this parser. The parser should remain just a library.

**Comment by kqvanity** [comment]
@NTBBloodbath I'm quite confused. Would a tool that builds on the parser be introduced or not? I think it's just a matter of mapping nvim options to flags

I'm generally looking forward to automate part of workflow, and this parser being interfaced with a scripting language/command, would help out.

**Comment by max397574** [comment]
if someone makes a tool then there will be one
but no matter whether there will be it won't be in this repository

**Comment by max397574** [comment]
there definitely is no intention to rewrite it to another language
not sure what you'd mean with another command

also not sure what you want to port it to

if you want to write a cli yourself just create a rust project and add this as a dependency
I guess clap would be your best option

**Comment by benlubas** [comment]
You could create bindings to lua with mlua if you want to use this parser in nvim

**Comment by benlubas** [comment]
I'll add that porting to another language will necessitate finding a parser combinator library in the target language which is similar to chumsky.

Really the best course of action depends on what it is you're trying to create and with what language.

**Comment by NTBBloodbath** [comment]
> @NTBBloodbath I'm quite confused. Would a tool that builds on the parser be introduced or not? I think it's just a matter of mapping nvim options to flags
> 
> I'm generally looking forward to automate part of workflow, and this parser being interfaced with a scripting language/command, would help out.

Yes, but the creation of such a tool is not within the responsibility of this repository or those who maintain the library. I closed the issue with the intention of leaving open only the issues that have to do directly with the parser, aka bugs and feature suggestions for it. I apology for any confusion caused in this regard, and anyone who wants to can use the library for whatever they want as well.

**Comment by kqvanity** [comment]
> rewrite it to another language

I was referring to wrapper bindings in a high-level scripting language like python (similar to lua in neovim)

> if you want to write a cli yourself just create a rust project and add this as a dependency

I would've done it already if I was familiar with rust & the library has documentation. 

Due to these two reason and the fact that
- You've already built lua wrappers around (so I guess it'll be just mapping options to flags)
- any superset features introduced to the parser would be ported to the CLI accordingly
- A no-brainer, but you're already the maintainer of the parser, so you're already familiar with its ins and outs

All in all, I do understand If there're no plans to support a command client whatsoever. I was just confused that the issue got abruptly closed.

> Really the best course of action depends on what it is you're trying to create and with what language.

Quite similar to how nb interacts with markdown notes. I just thought a wrapper in a scripting language would allow for more fine-grained conditional logic for automation.
