### ISSUE TITLE
Bug: discrepancies between the use of `ParagraphSegment` and `ParagraphSegmentToken`

### ISSUE THREAD

**Issue by NTBBloodbath** [nvim-neorg/rust-norg#6]
A paragraph is now `ParagraphSegment` but a heading title is still a `ParagraphSegmentToken` and it causes huge problems (perhaps this is a problem with other nodes that contains text, didn't test it very deeply yet). _It seems like it is hidden behind the ParagrahTokenList type._

cc @vhyrro

**Comment by vhyrro** [comment]
Fixed in latest commit :)
